# Setup

## Deps

```{r}
library(tidyverse)
library(httr2)
library(keyring)
```

## Vars

### Oauth

```{r}
tado_client_id <- "public-api-preview"
tado_oauth_url <- "https://auth.tado.com/oauth/token"
tado_oauth_key <- "4HJGRffVR8xb3XdEUQpjgZ1VplJi6Xgw"
username <- readLines("../.username.txt")
password <- key_get("tado", username)
```

```{r}
tado_client <- oauth_client(id = tado_client_id, 
                            token_url = tado_oauth_url,
                            secret = tado_oauth_key)
```

## Funs

```{r}
preview <- function(x, lvl = 3) {
  str(x, max.level = lvl, give.head = F, no.list = T)
}
```

# Tado API

## Endpoints

### my.tado `<home_id>`

`https://my.tado.com/api/v2/homes/1715394`

Base url of the house. Gives some basic information about the house like room count and basic settings.

```{r}
home <- "https://my.tado.com/api/v2/homes/1715394" |> 
  request() |> 
  req_oauth_password(tado_client, username, password, cache_disk = T) |> 
  req_perform() |> 
  resp_body_json()

preview(home, 1)
```

### hops.tado `rooms`

`https://hops.tado.com/homes/1715394/rooms`

rooms endpoint. gives a list of rooms

```{r}
rooms <- "https://hops.tado.com/homes/1715394/rooms" |> 
  request() |> 
  req_oauth_password(tado_client, username, password, cache_disk = T) |> 
  req_perform() |> 
  resp_body_json()

preview(rooms[[1]], 2)
```

### hops.tado `rooms/<room_id>/schedule`

`https://hops.tado.com/homes/1715394/rooms/1/schedule`

### hops.tado `rooms/<room_id>/dayReport`

`https://my.tado.com/api/v2/homes/1715394/zones/3/dayReport?date=2024-12-27`

### hops.tado `users`

`https://my.tado.com/api/v2/homes/1715394/users`

```{r}
users <- "https://my.tado.com/api/v2/homes/1715394/users" |> 
  request() |> 
  req_oauth_password(tado_client, username, password, cache_disk = T) |> 
  req_perform() |> 
  resp_body_json()

preview(users[[2]])
```



```{r}
token <- oauth_flow_password(tado_client,username, password)
```

```{r}
token$scope |> str_split(" ")
```
# Room report
```{r}
res <- "https://my.tado.com/api/v2/homes/1715394/zones/1/dayReport?date=2024-12-28" |>
  request() |> 
  req_oauth_password(client = tado_client, 
                     username = "ido.debaat@gmail.com",
                     password = "dybri9-movsys-wiTcyp",
                     cache_disk = T) |> 
  req_perform() |> 
  resp_body_json()
```

```{r}
res$measuredData$insideTemperature$dataPoints |> 
  list(data = _) |> 
  as_tibble() |> 
  unnest_wider(data) |> 
  unnest_wider(value) |> 
  mutate(timestamp = ymd_hms(timestamp)) |> 
  ggplot(aes(timestamp, celsius)) +
  geom_line() +
  scale_y_continuous(limits = c(0, 25)) +
  scale_x_datetime(date_labels = "%H:%M")
```
